### ISSUE TITLE
Lexer cannot lex things like +-1 or -(5). 

### ISSUE THREAD

**Issue by lukasberglund** [ayazhafiz/hgb#16]
It tries to evaluate all consecutive non-alphanumeric characters together, so in -(5), it tries to evaluate "-(" and returns invalid symbol.

**Comment by ayazhafiz** [comment]
@lukasberglund I'd like your feedback on how you want to handle this. My thought is to move `keywordToSymbol` to the lexer and write rules to resolve ambiguous symbols iteratively. This would look something like

```haskell
(tok, xs) = splitAt 1 str
case tok of
  "=" -> 
     (next, xs) = splitAt 1 x
     tok ++ xs
     case tok of
       "==" -> Symbol.DoubleEquals
       _ -> Symbol.Invalid
```

We could either create a separate function to take the "fast route" for alphanumeric keywords, which shouldn't need this kind of conditional mapping, or include them in this as well.

What do you think? Would love to hear if you have other ideas.

**Comment by lukasberglund** [comment]
This would work efficiently. My only reservation is that we kind of have to hardcode a decision tree that depends on the symbols we use. So if we added a symbol like "++" for incrementation, we would have to change not only the Builtin.hs and Symbol.hs file, but also the Lexer, which is less clean. 

An idea that I had is to change the way we deal with invalid symbols. For instance when the lexer tries to read "==+(" and fails, we send it into another method that tries to see if splitting the symbol would result in multiple valid symbols. That method would then try to read "==+", fail again then try to read "==" and succeed. 

The code would look something like this
```haskell
lexInvalid :: String -> String -> [Token]
lexInvalid sym remainder = let (newSym, lastElem) = removeLast sym
        in case symbolToString newSym of
       just symbol -> symbol
       _ -> lexInvalid newSym (lastElem:remainder)```

**Comment by ayazhafiz** [comment]
I thought about that idea, but my worry is this becomes rather expensive
very quickly.

To prevent duplication of code, we could just move all the string-to-token
conversion to the Lexer. What do you think?

**Comment by lukasberglund** [comment]
True, it does become expensive since we have to get to the end of the linked list every time. I guess your original solution is best. The coolest thing would be if we had a file of all symbols and what they meant and we used a script to write all our code related to those symbols based on that, that way we could avoid having to make sure that we get everything right and having to change a bunch of stuff manually. That would be a bit of work though.

Anyway, your original solution is best I think.

Do you think it would be possible to avoid duplication of code without putting all that in the lexer? For readability, I think it is important we keep our methods small. What do you think?

**Comment by ayazhafiz** [comment]
Maybe via the macro process you suggested in the first paragraph. If Haskell supports macro (unsure if it does), then we can probably go ahead and implement that.

**Comment by lukasberglund** [comment]
Oooh, wait I think I misunderstood you. Did you mean we should move all the stuff from the Builtin.hs and Symbol.hs to the lexer? If so I am on board.

**Comment by ayazhafiz** [comment]
Yes.

**Comment by lukasberglund** [comment]
Okay, let's just do that!
