### ISSUE TITLE
Parse arithmetic expressions

### ISSUE THREAD

**Issue by ayazhafiz** [ayazhafiz/hgb#20]
Parse simple arithmetic expressions, in as far as the arithmetic tokens provided by the Lexer.

#12

**Comment by lukasberglund** [comment]
I was going to push the full parser. I think I have arithmetic expressions down but I am halfway into adding functioncalls. Is it cool if I finish functioncalls and push that?

**Comment by ayazhafiz** [comment]
for sure


________________________________
От: lukasberglund <notifications@github.com>
Отправлено: суббота, января 18, 2020 7:49 PM
Кому: ayazhafiz/hgb
Копия: hafiz; Author
Тема: Re: [ayazhafiz/hgb] Parse arithmetic expressions (#20)


I was going to push the full parser. I think I have arithmetic expressions down but I am halfway into adding functioncalls. Is it cool if I finish functioncalls and push that?
