### ISSUE TITLE
Parser / Lexer will read "foo ()" as a function just like "foo()", it doesn't care whether there is a space seperating the two

### ISSUE THREAD

**Issue by lukasberglund** [ayazhafiz/hgb#25]

**Comment by ayazhafiz** [comment]
Do we want to make this a bug?

**Comment by lukasberglund** [comment]
Are you asking do we want to make this a bug or a feature of our compiler? Or are you asking do you want me to label this issue as a bug?

**Comment by ayazhafiz** [comment]
Both

**Comment by lukasberglund** [comment]
I just checked what python does and they seem to allow space in between. I don't see why we shouldn't allow it. Do you see any issues?

**Comment by ayazhafiz** [comment]
No. I think it's fine for now.

**Comment by ayazhafiz** [comment]
Can we close this?
