### ISSUE TITLE
Parse Function Declarations, Variable Assignments, and Variable Declarations

### ISSUE THREAD

**Issue by lukasberglund** [ayazhafiz/hgb#31]
I'd be happy to do this but @ayazhafiz if you want to get your hands dirty writing new code I'd be happy to let you take the lead.

**Comment by ayazhafiz** [comment]
Go for it! I have some other ideas for things to add, including better error messages. I will make issues for them soon.

**Comment by ayazhafiz** [comment]
@lukasberglund statements vs expressions: https://doc.rust-lang.org/reference/statements.html. We should differentiate between the two in our grammar, where a statement is a "line" of gingerbread (ending with `!`) and a statement can contain expressions.
