### ISSUE TITLE
Specify expected symbol kinds in error messages

### ISSUE THREAD

**Issue by ayazhafiz** [ayazhafiz/hgb#32]
It is not very helpful to show symbols in error messages as the symbol name; it is more useful to represent the symbol as the token that generates it.

**Comment by ayazhafiz** [comment]
Hey @lukasberglund. I've been thinking about this a bit more. So let's take an example:

```gb
5 + * 5!
```

Today when hgb parses this expression, we get the error

```
Error: expected Plus, Minus, LParen, Number, Name, or StrBound; got Times
```

I think what we want is something like

```
Error: expected an expression; got "*" at 4:5
```

What do you think? Should we place the expected tokens in the error message, like

```
Error: expected +, -, (, a number, an identifier, or "; got "*" at 4:5
```

I don't think we should, because for a user it is more correct that we expect an expression; the expression being `5 + ) * 5!` would not parse validly either, despite hgb saying that's what it expects.

The other thing is regarding the `4:5` span. I think later down the line we would want to include the line and column numbers (something like `line 1, column 4-5`). I think for now though, we can just keep it as the token indexes. We will have to put some thought into a good index -> line number implementation... that is actually non-trivial with UTF-8 vs. UTF-16 characters (not sure which one Haskell uses)

**Comment by lukasberglund** [comment]
The thing about the span makes sense. I'm having trouble understanding your
example. It seems to me like the parser is not saying that such an
expression would be acceptable. Am I missing something?

**Comment by ayazhafiz** [comment]
If we show the error

```
Error: expected +, -, (, a number, an identifier, or "; got "*" at 4:5
```

for `5 + * 5!`, then it may be considered that `5 + ( * 5!` should be a valid program because the compiler said it expected `(`. But this is not true; what the compiler really means is that it expected an expression, which so happens to begin with `(`.

**Comment by lukasberglund** [comment]
I see what you mean. Yeah I guess saying it expected an expression might be
better then.
