### ISSUE TITLE
Add char, array, and string (char array) type to gingerbread.

### ISSUE THREAD

**Issue by lukasberglund** [ayazhafiz/hgb#38]
As of right now the lexer does not lex keywords like "string" or "char". And the parser does not deal with chars, arrays, or strings.

**Comment by ayazhafiz** [comment]
Who is this assigned to? You or I?

**Comment by lukasberglund** [comment]
I can do it. You wanna do it?

**Comment by ayazhafiz** [comment]
Do char or array and I will do the other. Let's talk about strings. Are we sure that we want to represent strings as char arrays?

**Comment by ayazhafiz** [comment]
Talked offline, we will proceed with char arrays

**Comment by lukasberglund** [comment]
Actually can we reopen this char array thing? I was just thinking about how inconvenient arrays are in c/ c++, especially if you want to extend them. Do you think if we make strings be char arrays we risk making them hard to extend?

**Comment by ayazhafiz** [comment]
well we can provide our own wrapper of a string class so that we do not actually expose strings as chars arrays, that’s just the representation inside. what do you think?

________________________________
От: lukasberglund <notifications@github.com>
Отправлено: Wednesday, April 1, 2020 9:56:08 AM
Кому: ayazhafiz/hgb <hgb@noreply.github.com>
Копия: hafiz <ayaz.hafiz.1@gmail.com>; Comment <comment@noreply.github.com>
Тема: Re: [ayazhafiz/hgb] Add char, array, and string (char array) type to gingerbread. (#38)


Actually can we reopen this char array thing? I was just thinking about how inconvenient arrays are in c/ c++, especially if you want to extend them. Do you think if we make strings be char arrays we risk making them hard to extend?

**Comment by lukasberglund** [comment]
Yeah sounds good.

**Comment by lukasberglund** [comment]
In the Gingerbread doc we had List syntax be something like this
```
arr : [Int; 4] = [3, 2, 5, 1]
```
I think the `[Int; 4] ` isn't very nice and could use some improvement. What do you think?

**Comment by ayazhafiz** [comment]
what do you think are some ways we could improve it?

Maybe
```
Int[4]
Int<4>[]   # useful if we add support for generics later on
[Int]<4>
```

**Comment by lukasberglund** [comment]
Those seem like good suggestions. How is the second one useful generics?

**Comment by lukasberglund** [comment]
I kinda like the third option because it could allow people to create arrays that don't necessarily have a max size. What do you think of allowing that in gingerbread?

**Comment by ayazhafiz** [comment]
> Those seem like good suggestions. How is the second one useful generics?

Similar to how the third one is. We can say that an array is really of form `T<L>[]` where T and L are generics, or maybe even as `<T, L>[]` so it's `<Int, 4>[]`. This is kinda ridiculous, but just an idea

> I kinda like the third option because it could allow people to create arrays that don't necessarily have a max size. What do you think of allowing that in gingerbread?

I think it is better to explicitly differentiate between dynamically and statically sized arrays. If arrays can always be dynamically sized, then we should not have statically sized arrays.

**Comment by lukasberglund** [comment]
I personally am okay with just having dynamically sized arrays. How do you feel about it? Would it make the language less powerful?

**Comment by ayazhafiz** [comment]
I think it is okay. We can revisit it at a later date too.

________________________________
От: lukasberglund <notifications@github.com>
Отправлено: Monday, April 6, 2020 11:54:51 PM
Кому: ayazhafiz/hgb <hgb@noreply.github.com>
Копия: hafiz <ayaz.hafiz.1@gmail.com>; Assign <assign@noreply.github.com>
Тема: Re: [ayazhafiz/hgb] Add char, array, and string (char array) type to gingerbread. (#38)


I personally am okay with just having dynamically sized arrays. How do you feel about it? Would it make the language less powerful?

**Comment by ayazhafiz** [comment]
I think this is done
