### ISSUE TITLE
Parser does not distinguish between declarations and expressions

### ISSUE THREAD

**Issue by lukasberglund** [ayazhafiz/hgb#40]
In terms of grammar, declarations and expressions are not interchangeable. For instance, you shouldn't be able to add a variable declaration to a number like so `3 + a : Int`. 

I would recommend creating a type `Statement` and declaring a bit like this:
```haskell
data Statement = Expression Expression | Declaration Declaration
```
where `Declaration` and `Expression` are each their own datatype. Then we refactor the parser around that.

**Comment by ayazhafiz** [comment]
I agree! feel free to assign this to me if you’d like

**Comment by ayazhafiz** [comment]
Sorry I have been latent on this one. I will do it in the coming days, and definitely by the start of next week. It is blocking a number of things on the parser.

**Comment by lukasberglund** [comment]
Don't worry.
