### ISSUE TITLE
Get rid of the void keyword?

### ISSUE THREAD

**Issue by lukasberglund** [ayazhafiz/hgb#50]
Should we get rid of the void keyword? If a function does not return anything, we could just not write a type. Other than that I don't even know what the use of void really is.

**Comment by ayazhafiz** [comment]
i think it is fine to keep it for now. internally we will need some representation of `void` anyway for type checking; for instance in an expression like `a:int=makeInt()` if `makeInt` is a void function, hgb should complain. Exposing this to the user is benign in my opinion.
