### ISSUE TITLE
Add parser support for loops.

### ISSUE THREAD

**Issue by lukasberglund** [ayazhafiz/hgb#51]
We need to add parser support for while loops and for loops. Here is the syntax we had in mind
```
for i in (start .. limit) {
        print("number = ", i)!
}

while start <= limit {
        print("number = ", 1 + 1)!
	start = start + 1!
}

```
I'm really annoyed that Github hasn't added Syntax highlighting support for gingerbread yet. They are really behind the curve.

**Comment by ayazhafiz** [comment]
haha. we could [add it](https://github.com/github/linguist/blob/master/CONTRIBUTING.md)!

**Comment by lukasberglund** [comment]
@ayazhafiz what do you think of the slight changes I made to the list syntax in the for loop?

**Comment by ayazhafiz** [comment]
lgtm 👍
