### ISSUE TITLE
Remove "elseif" keyword in favor of "else if"

### ISSUE THREAD

**Issue by ayazhafiz** [ayazhafiz/hgb#63]
See https://github.com/ayazhafiz/hgb/pull/62#discussion_r414716919 for more context.

**Comment by ayazhafiz** [comment]
@lukasberglund actually maybe we should keep `elseif` as sugar for `else { if ... }`. The problem is that is we support `else if ...` we should also support any one-line expressions in the else block without the need for a bracketed-block. So something like `else 1 + 1!` would also be allowed. What do you think?

**Comment by lukasberglund** [comment]
I mean we don't _need_ to also support one-line expression, but I understand that it would be more consistent. I think keeping an `elseif` keyword is fine for now.
