### ISSUE TITLE
Function return expressions

### ISSUE THREAD

**Issue by ayazhafiz** [ayazhafiz/hgb#64]
Since Gingerbread is an expression-based language but can have statements, we should consider how return expressions are represented in functions without an explicit `return` statement.

I propose that the expression returned by a function is described by an expression, rather than a statement. The following examples demonstrate this:

```
fun foo() {
  let a : int = 1;
  a // returns a
}

fun foo() {
  let a : int = 1;
  a; // returns the void type _
}
```

**Comment by ayazhafiz** [comment]
Does this sound reasonable @lukasberglund?

**Comment by lukasberglund** [comment]
I don't quite understand the motivation behind that. What would be the benefit of having the returned statement not be delimited?

**Comment by ayazhafiz** [comment]
Makes it clearer that it’s an expression not a statement. `let a=1!` is a statement with no return type, `la=1` is an expression with return type 1. But I don’t think it matters too much either way, just allows for some separation of intent in the syntax. Saying “the last expression evaluated in a function” could be good enough too, but this means void functions would have to end with a void expression like `_;` or something

**Comment by lukasberglund** [comment]
Ah, gotcha.

Yeah that sounds good to me.

Best,
Lukas
